### PR TITLE
Fixes from the golang meetup

### PR DESCRIPTION
**Pull request by katzien**

### CODE REVIEW

**Comment by jpudney** [comment]
@katzien if you can revert the import names then we're good to go

**Comment by katzien** [comment]
D'uh, I'm a muppet, sorry - will fix now! What's the best strategy for this in the future?

**Comment by katzien** [comment]
I went with just having a separate branch with your namespace which I'll do any PRs from. Had to close this request as I couldn't change the base branch to the new one :)

**Comment by jpudney** [comment]
I'll check it out the new PR. I think in the future the best strategy is to clone this repo to `$GOPATH/github.com/jpudney/beerapp` and then you'd add a remote to your fork. This would then allow you to hack away on the this one but when you want to push your changes you just push to the fork. 

In this case, performing the following:

```
git clone git@github.com:jpudney/beerapp.git
git remote add fork git@github.com:katzien/beerapp.git
# make changes and commit
git push fork
```

Or something like that 😬

**Pull request closed without merging**
